[tool.black]
line-length = 88
include = '\.pyi?$'
exclude = '''
/(\.git|venv|build|dist)/
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
balanced_wrapping = true

[tool.flake8]
max-line-length = 88
ignore = "E203, W503" # Ignorer certaines erreurs
exclude = ".git,__pycache__,venv"

[tool.pytest.ini_options]
pythonpath = "src"
testpaths = ["tests"]
addopts = "-v"
